### ISSUE TITLE
[improvement] more settings

### ISSUE THREAD

**Issue by PavloPoliakov** [AStaroverov/vue-toast#1]
Hi,

Nice library, however some important points are missed (as I feel):
1. Option to set the location of the "toast" - left-top , right-top, left-bottom, right-bottom
2. Option to style the toasts (success, warning, info, alert)
3. Option to close the toast manually (the "x" button)
4. Option to show the permanent toast (which is possible to close manually, but it would not disappear after the delay)

Regards,

**Comment by AStaroverov** [comment]
Hi @PavelPolyakov,  1, 3, 4 in progress.
I think 2 point not yet flexible, It would be better if there was an ability to add class or style or type (success, warning, info, alert) to every toast

**Comment by flaird** [comment]
@AStaroverov Nice library! Any progress on this enhancement? Perhaps a develop branch that we can look at?
I think point 2 is possible with some config to either use bootstraps default types by setting it to `boostrap`, ie. `alert-success`, and that `default` will require you to create classes with some prefix, perhaps `vue-toast-success` with a fallback to the color it is now.

**Comment by AStaroverov** [comment]
Now complete, x button, themes, position, for release I must check at bugs
and improve api. 2 day maximum for this

пн, 8 февр. 2016 г., 9:49, sagaio notifications@github.com:
