### ISSUE TITLE
Vue 2 Laravel 5.3 Cannot read property 'showToast' of undefined

### ISSUE THREAD

**Issue by warmjaijai** [AStaroverov/vue-toast#11]
Followed how the instruction does but not working, please help

**.vue**

```
<template>
	<div>
    <vue-toast ref='toast'></vue-toast>
	</div>
</template>


<script>
  import VueToast from 'vue-toast';
  export default {
    components:{
      'vue-toast': VueToast,
    },
    created(){
      const toast = this.$refs.toast

      toast.showToast('Show me toast')
      toast.showToast('Show me toast again!')
    },
......
......
```

**ERROR (console log):**

> TypeError: Cannot read property 'showToast' of undefined
>     at VueComponent.created (eval at <anonymous> (app.js:327), <anonymous>:39:10)
>     at callHook (eval at <anonymous> (app.js:125), <anonymous>:2610:19)
>     at VueComponent.Vue._init (eval at <anonymous> (app.js:125), <anonymous>:3364:5)
>     at new VueComponent (eval at <anonymous> (app.js:125), <anonymous>:3483:12)
>     at createComponentInstanceForVnode (eval at <anonymous> (app.js:125), <anonymous>:2761:10)
>     at init (eval at <anonymous> (app.js:125), <anonymous>:2771:31)
>     at createComponent (eval at <anonymous> (app.js:125), <anonymous>:4120:9)
>     at createElm (eval at <anonymous> (app.js:125), <anonymous>:4063:9)
>     at createChildren (eval at <anonymous> (app.js:125), <anonymous>:4171:9)
>     at createElm (eval at <anonymous> (app.js:125), <anonymous>:4096:9)
> logError

**Comment by AStaroverov** [comment]
Try use mounted hook lifecycle instead created

чт, 9 февр. 2017 г., 6:13 warmjaijai <notifications@github.com>:

**Comment by warmjaijai** [comment]
Thanks for your response, I moved it to mounted the console log error not showing, however not toastr alert comes up either.

**Comment by warmjaijai** [comment]
I actually get the following error when I add import
  `import 'vue-toast/dist/vue-toast.min.css'`
back in my script

> Uncaught Error: Module parse failed: /Applications/XAMPP/xamppfiles/htdocs/soyegg/node_modules/vue-toast/dist/vue-toast.min.css Unexpected token (1:0)
> You may need an appropriate loader to handle this file type.

**Comment by AStaroverov** [comment]
U should add css loader for this file
Ex: import '!!style-loader!css-loader!vue-toast/dist/vue-toast.min.css'

пт, 10 февр. 2017 г., 15:59 warmjaijai <notifications@github.com>:

I actually get the following error when I add import
import 'vue-toast/dist/vue-toast.min.css'
back in my script

Uncaught Error: Module parse failed:
/Applications/XAMPP/xamppfiles/htdocs/soyegg/node_modules/vue-toast/dist/vue-toast.min.css
Unexpected token (1:0)
You may need an appropriate loader to handle this file type.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/AStaroverov/vue-toast/issues/11#issuecomment-278936382>,
or mute the thread

**Comment by warmjaijai** [comment]
sorry i am kind of new and never import css. I put in your code and got the following error

> Module not found: Error: Can't resolve 'style-loader' in '/Applications/XAMPP/xamppfiles/htdocs/soyegg/resources/assets/js/components'

can you explain it in a bit more details? or i guess that means i need some kind of style loader to load the file or something?

**Comment by warmjaijai** [comment]
i did some researches and refine my code but not sure if it is not working, there is no error shown on console log nor gulp watch. I think vue-loader actually includes style loader so I refine the code into the followings, please correct me if I am wrong on this:


`import '!!vue-style-loader!css-loader!vue-toast/dist/vue-toast.min.css'`

no errors shown, however toastr still does not show even i put it into mounted. I herewith show the full codes of mine

test.vue

```
<template>
	<div>
    hihi
    <vue-toast ref='toast'></vue-toast>
	</div>
</template>

<script>
  import '!!vue-style-loader!css-loader!vue-toast/dist/vue-toast.min.css'
  import VueToast from 'vue-toast'
  export default {
    components:{
      'vue-toast': VueToast,
    },
    data(){
      return{
        user:{},
        shop:{}
      }
    },
    props:[
    ],
    created(){
      this.getUserWithShop()
    },
    mounted(){
      const toast = this.$refs['toast']
      toast.showToast['hihi']
    },
    updated(){
    },
    methods:{
      getUserWithShop(){
        var vm = this
        vm.$http.get('/getUserWithShop').then((response)=>{
          vm.user = response.data.data.user
          vm.shop = response.data.data.shop
        })
      }
  	},
    computed:{

    }
  }
</script>
```

**Comment by AStaroverov** [comment]
``toast.showToast['hihi']`` - uncorrect
``toast.showToast('hihi')`` - correct
