### ISSUE TITLE
Throwing errors is killing our asset pipeline

### ISSUE THREAD

**Issue by EddieOne** [AStaroverov/vue-toast#12]
So this line https://github.com/AStaroverov/vue-toast/blob/master/dist/vue-toast.js#L470
It kills our assets pipeline for IE8.

Could you implement improved error handling @AStaroverov ?
https://www.sitepoint.com/proper-error-handling-javascript/

**Comment by AStaroverov** [comment]
Vue toast doesnt support ie8.

вт, 21 февр. 2017 г., 1:38 Eddie J <notifications@github.com>:

**Comment by EddieOne** [comment]
ok
