### ISSUE TITLE
A ClearAll() function would be nice here

### ISSUE THREAD

**Issue by SmarterPhoneLabs** [AStaroverov/vue-toast#15]
I have a case where i put the toaster in my root vue, but emit to it from other vues.
It makes great sense to do this, but when my view changes completely to another, it would be great to close all of the open toasts instead of waiting for them to expire on their own.

**Comment by AStaroverov** [comment]
Complete. Now vueToasts have method closeAll.

**Comment by SmarterPhoneLabs** [comment]
Sweet!
Ill pull the latest and give it a go!
Thanks

**Comment by SmarterPhoneLabs** [comment]
Amateur question on my side, did this automatically update your npm package as well, or do I need to use this github version instead?

**Comment by AStaroverov** [comment]
U can use npm packcage, just install latest version.

**Comment by SmarterPhoneLabs** [comment]
Nice!
