### ISSUE TITLE
Toast is obscured by popups and modals

### ISSUE THREAD

**Issue by eric-naguras** [AStaroverov/vue-toast#20]
Hi, thanks for this nice component.
Depending on your app of course, sometimes part of a toast is behind other element.

I put the toast component in App.vue, this seems the most logical place.
I do rather big modal forms in my app and longer toasts are behind my modals.

I solved this by adding a z-index with a large number.

```
<style>   
   .vue-toast-manager_container {   
       z-index: 1000;   
}
```
Maybe it's a good idea to add this to the component's CSS as I am probably not the only one.

**Comment by AStaroverov** [comment]
Sorry, but i dont think so. Default z-index may break someone apps/sites or behave unpredictably for anyone.
